# Generated by Django 4.2.4 on 2024-02-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='createAdmin',
        ),
    ]
